name: RaspSecurity
slug: raspsecurity
description: Face recognition service (FastAPI) as a Home Assistant add-on
version: "0.1.0"
url: https://github.com/MaHaoxuantb/RaspSecurity
arch:
  - aarch64
  - amd64
  - armv7
  - i386

startup: services
boot: auto
init: false

# Home Assistant will substitute {arch}
image: "ghcr.io/mahaoxuantb/raspsecurity-raspsecurity-{arch}"

ports:
  3000/tcp: 3000

options:
  me_url: ""
  user: ""
  pass: ""
  ha_url: ""
  token: ""
  security_key: ""
schema:
  me_url: str
  user: str
  pass: password
  ha_url: str
  token: password
  security_key: password

# If you need host networking or device access later, you can add:
# host_network: true
# devices:
#   - /dev/video0
